---
language: python
python: "3.9"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python3-pip

install:
  # Install ansible
  - pip3 install ansible==2.10 molecule-ec2 pytest-testinfra boto boto3 awscli
  
  # configure AWS CLI
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY
  - aws configure set aws_secret_access_key $AWS_SECRET_KEY
  - aws configure set default.region $AWS_DEFAULT_REGION
  # show AWS CLI config
  - aws sts get-caller-identity

  # Check ansible version
  - molecule --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  
script:
  # Perform molecule test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
